<?php

declare(strict_types=1);

const THEME_DARK = [
    'bg' => '#080c14',
    'headerBg' => 'linear-gradient(135deg,#0f1a2e,#1a1030,#0d1520)',
    'text' => '#eef2f7',
    'textMuted' => '#b0c0d0',
    'textFaint' => '#7088a0',
    'textBody' => '#d0dae6',
    'bold' => '#ffffff',
    'border' => '#ffffff18',
    'tabBg' => '#ffffff08',
    'tabActive' => '#648cdc30',
    'tabText' => '#88bbff',
    'cardBg' => '08',
    'svgArrow' => '#99aabb',
    'svgRowBg' => '.04',
    'legendText' => '#99aabb',
    'drugText' => '#8899aa',
    'drugLabel' => '#c0d0e0',
    'emptyText' => '#6688aa',
    'srcText' => '#99aabb',
    'srcCat' => '#88bbee',
    'nodeHoverAlpha' => '38',
    'nodeAlpha' => '1a',
    'cytHoverAlpha' => '40',
    'cytAlpha' => '22',
    'recAlpha' => '18',
    'jakAlpha' => '1a',
    'statAlpha' => '1a',
    'targetAlpha' => '12',
    'drugBg' => 'rgba(68,204,68,.08)',
    'drugBorder' => '#44dd44',
    'arrowWidth' => '1.2',
    'arrowOpacity' => '.55',
    'arrowDashOpacity' => '.45',
    'guideLineOpacity' => '.18',
    'guideLineWidth' => '.4',
    'cellStrokeWidth' => '1.8',
    'cytStrokeWidth' => '1.2',
    'recStrokeWidth' => '1',
    'toggleIcon' => "\u2600\uFE0F",
];

const THEME_LIGHT = [
    'bg' => '#f0f2f6',
    'headerBg' => 'linear-gradient(135deg,#dde4f0,#e8ddef,#f0e4dd)',
    'text' => '#111820',
    'textMuted' => '#334455',
    'textFaint' => '#556677',
    'textBody' => '#1a2535',
    'bold' => '#000000',
    'border' => '#00000018',
    'tabBg' => '#00000008',
    'tabActive' => '#3366cc20',
    'tabText' => '#2255bb',
    'cardBg' => '15',
    'svgArrow' => '#445566',
    'svgRowBg' => '.07',
    'legendText' => '#334455',
    'drugText' => '#334455',
    'drugLabel' => '#1a2535',
    'emptyText' => '#556677',
    'srcText' => '#334455',
    'srcCat' => '#1144aa',
    'nodeHoverAlpha' => '40',
    'nodeAlpha' => '25',
    'cytHoverAlpha' => '48',
    'cytAlpha' => '28',
    'recAlpha' => '1a',
    'jakAlpha' => '1e',
    'statAlpha' => '1e',
    'targetAlpha' => '14',
    'drugBg' => 'rgba(20,140,20,.1)',
    'drugBorder' => '#228833',
    'arrowWidth' => '1.4',
    'arrowOpacity' => '.65',
    'arrowDashOpacity' => '.5',
    'guideLineOpacity' => '.2',
    'guideLineWidth' => '.5',
    'cellStrokeWidth' => '2',
    'cytStrokeWidth' => '1.4',
    'recStrokeWidth' => '1.2',
    'toggleIcon' => "\uD83C\uDF19",
];

const CATEGORY_COLORS = [
    'Zelle' => '#4488ff',
    'Cell' => '#4488ff',
    'Signalweg' => '#ff6644',
    'Pathway' => '#ff6644',
    'Kinase' => '#22bb88',
    'Erkrankung' => '#cc44aa',
    'Disease' => '#cc44aa',
];

/**
 * Supported languages.
 * To add a new language: create content/<code>/ with cells/, pathways/, kinases/, diseases/
 * subfolders, then add an entry here.
 */
const LANGUAGES = [
    'de' => ['label' => 'Deutsch', 'flag' => 'DE'],
    'en' => ['label' => 'English', 'flag' => 'EN'],
    // 'fr' => ['label' => 'Français', 'flag' => 'FR'],
    // 'es' => ['label' => 'Español', 'flag' => 'ES'],
];
